[build]
  publish = "."

[[redirects]]
  from = "/product/*"
  to = "/product.html"
  status = 200

[[headers]]
  for = "/products/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
